version: '3'
services:
    appregister:
      container_name: app.register
      image: php:7.2-cli
      build:
        context: ./docker/php
      ports:
        - 8001:8001
      depends_on:
      - dbmysql
      links:
        - dbmysql
      command: sh /var/www/setup.sh
      environment:
        MYSQL_ROOT_HOST: $MYSQL_ROOT_HOST
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        APP_ID: $APP_ID
        APP_ENV: $APP_ENV
        APP_URL: $APP_URL
        API_TOKEN: $API_TOKEN
    dbmysql:
      image: mysql:5.6
      build:
        context: ./docker/mysql
      ports:
        - 33060:3306
      volumes:
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_HOST: $MYSQL_ROOT_HOST
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
volumes:
  dbmysql:
