GET http://localhost:8001/v1/register/1
X-Token: d2a57dc1d883fd21fb9951699df71cc7

###
GET http://localhost:8001/v1/register/1/bill
X-Token: d2a57dc1d883fd21fb9951699df71cc7

###
GET http://localhost:8001/v1/register/1/bill/9
X-Token: d2a57dc1d883fd21fb9951699df71cc7

### Send POST request with form body
POST http://localhost:8001/v1/register/1/bill
X-Token: d2a57dc1d883fd21fb9951699df71cc7

price=30.50&amount=1

### Send POST request with json body
POST http://localhost:8001/v1/register/1/bill
X-Token: d2a57dc1d883fd21fb9951699df71cc7
Content-Type: application/json

{
  "price": 85.50
}

### Send DELETE request with bill_id in uri
DELETE http://localhost:8001/v1/register/1/bill/5
X-Token: d2a57dc1d883fd21fb9951699df71cc7
